config/routes.rb
EngPort::Application.routes.draw do
  resources :announcements do
  	collection do
      get :export
      get :meeting_announcements
    end

  end

  root controller: 'announcements', action: 'index'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  validates_presence_of :title
  acts_as_taggable
end

app/controllers/announcements_controller.rb
require "prawn"

class AnnouncementsController < ApplicationController
  http_basic_authenticate_with name: "Clarisse", password: ENV['ENGPORT_PASS'], only: :new

  def new
    @announcement = Announcement.new
  end

  def index
    if params[:auto_complete]
      return render json: [].to_json if params[:q].blank?

      @meeting_announcements = Announcement.all.select{|a| a.tag_list.include?("#{params[:meeting]}")}
      @announcements = []

      while (match = FuzzyMatch.new(@meeting_announcements, read: :description).find(params[:q]))
        @announcements << match
        @meeting_announcements = @meeting_announcements - [match]
      end

      while (match = FuzzyMatch.new(@meeting_announcements, read: :tag_list).find(params[:q]))
        @announcements << match
        @meeting_announcements = @meeting_announcements - [match]
      end

      while (match = FuzzyMatch.new(@meeting_announcements, read: :title).find(params[:q]))
        @announcements << match
        @meeting_announcements = @meeting_announcements - [match]
      end

      @announcements.map! do |r|
        {
          value: r.title,
          id: r.id
        }
      end

      return render json: @announcements
    else
      @announcements = Announcement.all
    end
  end

  def create
    @announcement = Announcement.new( description: params[:announcement][:description], title: params[:announcement][:title], notes: params[:announcement][:notes], location: params[:announcement][:location] )
    @announcement.date = DateTime.parse(params[:date_entry] + " " + params[:time_entry]) if params[:date_entry].present? && params[:time_entry].present?
    @announcement.tag_list += params[:tag_entry].split('#')

    if @announcement.save
      redirect_to new_announcement_path, notice: 'New Announcement Successfully Added.'
    else
      flash[:error] = "Error Creating Announcement"
      render action: 'new'
    end
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def show
   @announcement = Announcement.find(params[:id])
  end

  def update
    @announcement = Announcement.find(params[:id])
    if @announcement.update_attributes(params.require(:announcement).permit(:title, :description, :date, :notes, :location))
      redirect_to action: 'show', id: @announcement
    else
      render action: 'edit'
    end
  end

  def destroy
    Announcement.find(params[:id]).destroy
    redirect_to action: 'index'
  end

  def meeting_announcements
    if params[:meeting] == 'all'
      render json: Announcement.all do |r|
        {
	  value: r.title,
	  id: r.id
        }
      end
    else
      render json: Announcement.all.select{|a| a.tag_list.include?(params[:meeting])}.map! do |r|
        {
          value: r.title,
          id: r.id
        }
      end
    end
  end

  def print_announcements( category, announcements, pdf )
    if announcements.size > 0
      pdf.pad_top(40) {
        pdf.font_size(20) {
          pdf.text category, :style => :bold
	}
      }
    end
    announcements_table = []
    announcements.each do |announce|
      if announce.date != nil
        date_table = pdf.make_table( [[announce.date.strftime( '%b' )],[announce.date.strftime( '%l:%M%P' )]], cell_style: {borders: [], padding: [0, 0, 0, 10]} ) do
	  style( row(0), size: 16 )
	  style( row(1), size: 8 )
        end
        left_table = pdf.make_table( [[ announce.date.strftime( '%e' ), date_table], [{content: announce.location, colspan: 2}]], cell_style: { width: 45, borders: [] } ) do
	  style( column(0), size: 34, font_style: :bold, text_color: '828282', align: :right, padding: 0 )
	  style( row(0), height: 35 )
	  style( row(1), size: 12, width: 40, borders: [], font_style: :bold, text_color: '000000', align: :right, padding: [0, 10, 0, 0] )
	end
      else
        left_table = pdf.make_table([['',''], [{content: announce.location, colspan: 2}]], cell_style: {borders: [], padding: [0, 10, 0, 0], width: 45} ) do
	  style( row(0), height: 35 )
	  style( row(1), size: 12, width: 40, borders: [], font_style: :bold, align: :right, padding: [0,10,0,0] )
	end
      end
      announce.notes = 'P.S.' + announce.notes if announce.notes
      right_table = pdf.make_table( [[announce.title], [announce.description], [announce.notes.to_s] ], cell_style: {width: 450, borders: [:left], padding: [0, 0, 0, 10] } ) do
        style( row(0), font_style: :bold, size: 14 )
	style( row(2), font_style: :italic, padding: [5, 0, 0, 10] )
      end
      announcements_table.push( [ left_table, right_table ] )
    end
    if announcements.size > 0
      pdf.table( announcements_table, cell_style: { borders: [:top, :bottom], border_lines: [:dotted, :solid, :dotted, :solid], padding: [ 10, 0, 10, 0] } ) do
        style( column(0), borders:[:right, :top, :bottom], border_lines: [:dotted, :solid, :dotted, :solid] )
      end
    end
  end

  def export
    announcements = params[:ids].split(',').map{|id| Announcement.find(id)}
    unless params[:notes].nil?
      notes = params[:notes].split(',,')
      notes.each_with_index do |note, i|
        announcements[i].notes = note
      end
    end

    events = announcements.select{ |e| e.tag_list.include?('event') }
    events.sort{|vn| vn.date.to_f }

    engineering_opportunities = announcements.select{ |e| e.tag_list.include?('engopportunity') }
    engineering_opportunities.sort{|vn| vn.date.to_f }

    fyis = announcements.select{ |e| e.tag_list.include?('fyi') }
    fyis.sort{|vn| vn.date.to_f }

    other = announcements.reject{ |e| e.tag_list.include?('event') || e.tag_list.include?('engopportunity') || e.tag_list.include?('fyi') }
    other.sort{|vn| vn.date.to_f }
    pdf = Prawn::Document.new
    pdf.image "#{Rails.root}/app/assets/images/EngSoc_header.jpg", position: :center, width: 300

    print_announcements( 'EVENTS', events, pdf )
    print_announcements( 'ENGINEERING OPPORTUNITIES', engineering_opportunities, pdf )
    print_announcements( 'FYI\'S', fyis, pdf )
    print_announcements( 'OTHER', other, pdf )

    @filename = 'public/announcements_' + (0...8).map { (65 + rand(26)).chr }.join + '.pdf'
    pdf.render_file @filename

    if params[:method] == 'dl'
      send_file @filename, filename: 'announcements.pdf'
    elsif params[:method] == 'tw'
      url = "http://twitter.com/share?text=#{@filename}"
      redirect_to url
    else
      url = 'http://www.facebook.com/sharer/sharer.php?u=' + request.env['HTTP_HOST'] + '/' + @filename
      redirect_to url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/announcements/edit.html.haml
%h1= 'Edit an announcement here'
= form_for @announcement, action: 'update', class: 'form-horizontal' do |f| 
  .form-group
    = f.label 'Title', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label 'Date (optional)', class: 'col-sm-2 control-label'
    = f.date_select :date, class: 'col-sm-10'
  .form-group
    = f.label 'Description', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label 'Special notes', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :notes, class: 'form-control'
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit 'Save', class: 'btn btn-primary'

app/views/announcements/index.html.haml
= javascript_include_tag 'index'
= javascript_include_tag "announcements/announcements"

.wrapper#announcements_page
  .container
    %h1= 'Choose your announcements'
    %ul.nav.nav-pills.center#meetings
      - for i in 1..6
        %li(id="meeting#{i}" class="#{i == 1 ? "active" : ""}")
          %a.meeting_link= "Meeting #{i}"
      %li(id="meeting_all")
        %a.meeting_link= "All"
    .search_container.row
      %form#announcement-search.col-xs-10.pull-left{ method: "GET", action: "/announcements" }
        %input.form-control#announcement-search-query{ type: "text", placeholder: "#search", name: "q", autocomplete: "off" }
      %button.btn.btn-primary.pull-right.select_all="Select All"
    #export_bar
      =link_to "Export", '#', id: 'dl', class: 'btn btn-default export'
      =link_to "Share on Facebook", '#', id: 'fb', class: 'btn btn-default export'
      =link_to "Share on Twitter", '#', id: 'tw', class: 'btn btn-default export'
    #wookmark_container
      - @announcements.each do |announcement|
        .event{data: {id: announcement.id}}
          - if announcement.date
            %span.date.date_format= announcement.date.to_time.to_i
          - if announcement.location
            %p= announcement.location
          .clearfix
          %h3= announcement.title
          %p= announcement.description
          = text_field_tag :note_entry, '', class: 'form-control clearfix notes', placeholder: 'Special notes'
          - announcement.tag_list.each do |tag|
            %span.caption= '#' + tag
          %br

app/views/announcements/new.html.haml
.wrapper#new_announcement_page

  = render partial: 'layouts/messages'
  
  .container
    .col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3#new_form
      %h1= 'New Announcement'
      - @announcement.errors.full_messages.each do |e|
        %li{style: "padding-left: 15px"}=e
      = form_for @announcement do |f|
        .form-group
          = f.label :title, 'Title', class: 'col-sm-3 control-label'
          .col-sm-9
            = f.text_field :title, class: 'form-control'
        .form-group
          = label_tag :date_label, 'Date (optional)', class: 'col-sm-3 control-label'
          .col-sm-9
            = text_field_tag :date_entry, '', type: :date, class: 'form-control'
        .form-group
          = label_tag :time_label, 'Time (optional)', class: 'col-sm-3 control-label'
          .col-sm-9
            = text_field_tag :time_entry, '', type: :time, class: 'form-control'
        .form-group
          = f.label :location, 'Location (optional)', class: 'col-sm-3 control-label'
          .col-sm-9
            = f.text_field :location, class: 'form-control'
        .form-group
          = f.label :description, 'Description', class: 'col-sm-3 control-label'
          .col-sm-9
            = f.text_area :description, class: 'form-control'
        .form-group
          = label_tag :tag_label, 'Tags', class: 'col-sm-3 control-label'
          .col-sm-9
            = text_field_tag :tag_entry, '', class: 'form-control', placeholder: '#awesome #youdabombclarisse'
        .form-group
          .col-sm-10.col-sm-offset-1
            = f.submit 'Add', class: 'btn btn-primary'

app/views/announcements/show.html.haml
= javascript_include_tag 'search'
%h1= @announcement.title
%h2= @announcement.description
=link_to "Delete", announcement_path(@announcement), method: 'delete', confirm: "Ya sure?"

%form#announcement-search{method: "GET", action: "/announcements"}
  %input#announcement-search-query{type: "text", placeholder: "Search", name: "q", autocomplete: "off"}

:css
  #announcement-search-typeahead2 {
    color: $mid-gray;
    min-width: 300px;
    .active a {
      background-color: blue;
    }
  }

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EngPort</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</html>